Repository huff-language/huff-docs, pull requests merged in 2022-07, with the labels that each got.

#8 feat: Example Enhancements + Added Docs
  src/get-started/huff-by-example/README.md
Labels: documentation

#28 docs: update example
  src/get-started/huff-by-example/README.md
Labels: bug, getting-started

#29 fix: tutorial link
  src/get-started/compiling/README.md
Labels: bug, tutorial

#30 fix: Search Icon
  src/.vuepress/styles/index.styl
Labels: bug

#32 feat: Natspec Comment Guide
  src/style-guide/overview/README.md
Labels: styleguide
